### ISSUE TITLE
Fake tool

### ISSUE THREAD

**Issue by MHasnain00** [Hoodmaster2/SOCIAL-MEDIA-#1]
You are just printing all the lines without doing anything like simulator. Don't try to make people fool.

**Comment by Hoodmaster2** [comment]
yes 😂 it's just printing cause I didn't expect anyone to be on GitHub without a basic knowledge of printing statements, I'm sorry this account if for education center that I teach and that's what they created and this is an open source don't expect anything fancy from here.
